services:
  model-api:
    image: harga-pangan-model-api
    expose:
      - "8080"
    deploy:
      replicas: 3
    networks:
      - mlops-network

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - model-api
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge